kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry:50000".tls]
      ca_file = "/etc/containerd/certs/cert.pem"
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
    - hostPath: /tmp/registryStorage
      containerPath: /registryStorage
    - containerPath: /etc/containerd/certs
      hostPath: %CERT_PATH%
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: %HTTP_PORT%
    protocol: TCP
  - containerPort: 443
    hostPort: %HTTPS_PORT%
    protocol: TCP
