kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
      - hostPath: /tmp/registryStorage
        containerPath: /registryStorage
  extraPortMappings:
  - containerPort: 80
    hostPort: 8083
    protocol: TCP
  - containerPort: 443
    hostPort: 8446
    protocol: TCP
